import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../styles/globals.css";
import {Navbar} from "@/components/Navbar";
import {Footer} from "@/components/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "G Mon Stage",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
        <body className={inter.className}>
        <div className={`bg-dark pt-8 ${inter.className}`}>
            <Navbar/>
            <main className="container mx-auto flex min-h-screen flex-col gap-32 px-4 pt-24 md:gap-64">
                {children}
            </main>
            <Footer/>
        </div>
        </body>
        </html>
    );
}
